### ISSUE TITLE
Error/crash after scroll up in console history on fresh start

### ISSUE THREAD

**Issue by redbau** [mark2devel/mark2#179]
Got this error scrolling up in console after a fresh server start:

```Traceback (most recent call last):
  File "/home/minecraft/mark2/mark2", line 6, in <module>
    sys.exit(main())
  File "/home/minecraft/mark2/mk2/launcher.py", line 624, in main
    command.start()
  File "/home/minecraft/mark2/mk2/launcher.py", line 126, in start
    self.run()
  File "/home/minecraft/mark2/mk2/launcher.py", line 508, in run
    f.main()
  File "/home/minecraft/mark2/mk2/user_client.py", line 592, in main
    self.ui.main()
  File "/home/minecraft/mark2/mk2/user_client.py", line 273, in main
    self.loop.run()
  File "/usr/local/lib/python3.10/dist-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/local/lib/python3.10/dist-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.10/dist-packages/urwid/main_loop.py", line 1346, in run
    reraise(*exc_info)
  File "/usr/local/lib/python3.10/dist-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/local/lib/python3.10/dist-packages/urwid/main_loop.py", line 1360, in wrapper
    rval = f(*args,**kargs)
  File "/usr/local/lib/python3.10/dist-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/usr/local/lib/python3.10/dist-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/lib/python3.10/dist-packages/urwid/main_loop.py", line 409, in _update
    keys = self.input_filter(keys, raw)
  File "/usr/local/lib/python3.10/dist-packages/urwid/main_loop.py", line 549, in input_filter
    return self._input_filter(keys, raw)
  File "/home/minecraft/mark2/mk2/user_client.py", line 291, in filter_input
    self.set_focused()
  File "/home/minecraft/mark2/mk2/user_client.py", line 369, in set_focused
    attr = attr.copy_modified(fg="default")
AttributeError: 'AttrSpec' object has no attribute 'copy_modified'```

**Comment by Column01** [comment]
This is basically the same bug as #175

As stupid as this sounds, have ypu tried not scrolling up immediately in the console when it starts?

Does it happen every time you scroll up?
